language: java
sudo: false
install: true

jdk:
  - oraclejdk8

script:
  # JaCoCo is used to have code coverage, the agent has to be activated
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.projectKey=TraningCenter2018-2019_V_V_Denisov_second_task -Dsonar.organization=traningcenter2018-2019 -Dsonar.host.url=https://sonarcloud.io  -Dsonar.login=f7392889a70017550cd5d8e50dcb5564cff84f73

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
